### PR TITLE
Indexing

### PR DESCRIPTION
**Pull request by row11**
@row11 	adding elastic search indexing tools (moved from aristo project)

### CODE REVIEW

**Comment by row11** [comment]
Just copied from aristo and fixed dependencies!

**Comment by sbhaktha** [comment]
`BuildCorpusIndex` needs an `ExecutionContext`? Build fails. Assigning back to you to fix! Otherwise looks good.

**Comment by row11** [comment]
Merging!

**Comment by sbhaktha** [comment]
Awesome!

**Pull request merged**
