### PR TITLE
Release 1.0.7

### PR DESCRIPTION
**Pull request by cristipp**

### CODE REVIEW

**Comment by jkinkead** [comment]
Uh-oh, looks like `test:format` needs to be run before this will release on shippable . . .

**Comment by cristipp** [comment]
Fix PR: https://github.com/allenai/common/pull/133

I honestly do not understand how our format hooks work. On euclid, every
time I try to git commit, it fails because of sbt format so I have to do it
twice. On common, it doesn't appear to run sbt format at all. Perhaps I
have an outdated hook?

```
$ ls -l  ~/.git_template/hooks
total 16400
-rwxr-xr-x  1 cristipp  staff     2940 Feb 13 14:52 pre-commit
-rw-r--r--  1 cristipp  staff  8389062 Feb 16 10:34 scalariform.jar
```

**Comment by cristipp** [comment]
Updated, 1.0.8, PTAL

**Comment by jkinkead** [comment]
If you're not seeing auto-formatting in `common`, it may be that you created the git repo before you had your templates set up. You can run `git init` in the project root to re-initialize it.

Release LGTM, merging!

**Pull request merged**
