### PR TITLE
Color source and sink nodes

### PR DESCRIPTION
**Pull request by schmmd**
I implemented a few items in [our list of improvements to the visualization diagram](https://trello.com/c/F7yqNBQt/97-improve-pipeline-visualization).

* Upgraded to the latest version of dagre (0.4.2).
* Color the source and sink nodes distinctively.

### CODE REVIEW

**Comment by schmmd** [comment]
Edges are not curved anymore and boxes don't have rounded edges.  I might fine tune this with @codeviking tomorrow. @jakemannix FYI.

image
image

**Comment by schmmd** [comment]
I changed the fill color so it doesn't suck so much.  I'll iterate with Sam tomorrow.

image

**Comment by jakemannix** [comment]
Oooh, cool, lookin' good so far!

On Thu, Feb 12, 2015 at 5:16 PM, Michael Schmitz <notifications@github.com>
wrote:

> I changed the fill color so it doesn't suck so much. I'll iterate with Sam
> tomorrow.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/954798/6180520/f03294e8-b2da-11e4-821c-70e22626479f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/allenai/common/pull/90#issuecomment-74188219>.
>



-- 

  -jake

**Comment by rodneykinney** [comment]
Coloring is great!  Assigning back to you.  Iterate with Sam and merge

**Comment by schmmd** [comment]
@codeviking mind looking at the last two commits?

**Pull request merged**
