### PR TITLE
Release

### PR DESCRIPTION
**Pull request by cristipp**
Release v1.0.1, please double check.

### CODE REVIEW

**Comment by schmmd** [comment]
The change is binary compatible, so this change is correct.

**Comment by schmmd** [comment]
[Before](http://ai2-s2.s3.amazonaws.com/pipeline/output/publish/summary/BuildIndexFromPdfs-2015-05-21-11-07-29.html)
[After](http://ai2-s2.s3.amazonaws.com/pipeline/output/publish/summary/BuildIndexFromPdfs-2015-05-21-18-54-10.html)

The MetadataPR files look identical.

**Comment by schmmd** [comment]
@rodneykinney FYI

**Comment by jakemannix** [comment]
rockin!

**Pull request merged**
